---

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    open-pull-requests-limit: 10
    directory: "source/StopWatch"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    open-pull-requests-limit: 10
    directory: "source/StopWatchSetup"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    open-pull-requests-limit: 10
    directory: "source/StopWatchTest"
    schedule:
      interval: "daily"
